Blog post on PyWPS 4.2
geopython/pywps.org pull request #7
Opened 2018-12-19 16:53 UTC by ldesousa

A bit long, but it is worthy spending the time to tell the story.

2018-12-19 17:12 UTC, jachym approved these changes
Nice written, thanks

2018-12-20 10:03 UTC, cehbrecht requested changes
Sounds good :) See comments (typos, ...).

2018-12-20 10:03 UTC, cehbrecht commented on _posts/2018-12-20-pywps-4.2.0-released.md
> +A word also regarding the WSGI applications provided as exemple services using PyWPS. [`pywps-flask`](https://github.com/geopython/pywps-flask) remains the most popular but a backlog of small issues
typo: example

2018-12-20 10:03 UTC, cehbrecht commented on _posts/2018-12-20-pywps-4.2.0-released.md
> +Finally the PSC would like to thank everyone that has contributed to PyWPS these past two years: from those doing the code heavy lifting, to testers, bug reporters, documentation contributors. Every
typo: "... what [it] is today!"

2018-12-20 10:03 UTC, cehbrecht commented on _posts/2018-12-20-pywps-4.2.0-released.md
> +PyWPS remains fully reliant on *pro bono* contributions without any sort of commercial organisation around it. This means the project largely depends on how the community is able to contribute an any
?: ... able to contribute [an any given]

2018-12-20 10:03 UTC, cehbrecht commented on _posts/2018-12-20-pywps-4.2.0-released.md
> +Relying on voluntary contributions does not mean progress is slow, much to the contrary. In recent times PyWPS has had more simultaneous contributors than at any moment before in its history. This is
?: ... PSC was expanded to six (members instead of elements?),

2018-12-23 17:30 UTC, merged